import { Professional, Chapter } from './types';

export const professionals: Professional[] = [
  // === MILANO ===
  {
    id: 'mi-001',
    name: 'Marco Ferretti',
    profession: 'Avvocato Civilista',
    category: 'Avvocato',
    city: 'Milano',
    chapter: 'NDP Milano Duomo',
    phone: '+39 02 8765 4321',
    email: 'm.ferretti@studioferretti.it',
    bio: 'Avvocato con oltre 15 anni di esperienza in diritto civile e societario. Specializzato nella tutela di PMI e startup nel contesto nazionale e internazionale.',
    specialties: ['diritto civile', 'diritto societario', 'contratti', 'PMI', 'startup', 'fusioni', 'acquisizioni'],
    yearsInBNI: 7,
    referralsGiven: 214,
    rating: 4.9,
  },
  {
    id: 'mi-002',
    name: 'Giulia Rossi',
    profession: 'Commercialista & Revisore',
    category: 'Commercialista',
    city: 'Milano',
    chapter: 'NDP Milano Duomo',
    phone: '+39 02 3456 7890',
    email: 'g.rossi@studiofiscalerossi.it',
    bio: 'Commercialista iscritta all\'Ordine di Milano, esperta in fiscalità d\'impresa, contabilità e pianificazione fiscale. Partner di riferimento per oltre 80 aziende.',
    specialties: ['fiscalità', 'contabilità', 'bilancio', 'tasse', 'IVA', 'pianificazione fiscale', 'dichiarazioni'],
    yearsInBNI: 5,
    referralsGiven: 189,
    rating: 4.8,
  },
  {
    id: 'mi-003',
    name: 'Alessandro Conti',
    profession: 'Agente Immobiliare Luxury',
    category: 'Agente Immobiliare',
    city: 'Milano',
    chapter: 'NDP Milano Brera',
    phone: '+39 02 9876 5432',
    email: 'a.conti@contirealestate.it',
    bio: 'Specializzato nel mercato residenziale di lusso milanese. In 12 anni ha mediato oltre 300 transazioni nel centro storico, Brera e Navigli.',
    specialties: ['immobili di lusso', 'residenziale', 'affitti', 'vendita', 'centro storico', 'investimenti immobiliari'],
    yearsInBNI: 4,
    referralsGiven: 156,
    rating: 4.7,
  },
  {
    id: 'mi-004',
    name: 'Federica Lombardi',
    profession: 'Consulente Assicurativa',
    category: 'Assicuratore',
    city: 'Milano',
    chapter: 'NDP Milano Brera',
    phone: '+39 02 5432 1098',
    email: 'f.lombardi@lombardi-assicurazioni.it',
    bio: 'Consulente assicurativa indipendente specializzata in polizze vita, responsabilità civile professionale e protezione aziendale. Più di 500 clienti attivi.',
    specialties: ['assicurazione vita', 'RC professionale', 'polizze aziendali', 'previdenza', 'protezione'],
    yearsInBNI: 6,
    referralsGiven: 201,
    rating: 4.9,
  },
  {
    id: 'mi-005',
    name: 'Luca Bianchi',
    profession: 'CTO & Consulente IT',
    category: 'Consulente IT',
    city: 'Milano',
    chapter: 'NDP Milano Duomo',
    phone: '+39 02 6789 0123',
    email: 'l.bianchi@techsolutions.it',
    bio: 'Ex CTO di startup fintech, ora consulente IT freelance. Esperto in trasformazione digitale, cybersecurity e sviluppo software per PMI.',
    specialties: ['trasformazione digitale', 'cybersecurity', 'cloud', 'software', 'AI', 'automazione', 'ERP'],
    yearsInBNI: 3,
    referralsGiven: 98,
    rating: 4.8,
  },
  {
    id: 'mi-006',
    name: 'Chiara Marino',
    profession: 'Architetto d\'Interni',
    category: 'Architetto',
    city: 'Milano',
    chapter: 'NDP Milano Brera',
    phone: '+39 02 2345 6789',
    email: 'c.marino@marinoarchitettura.it',
    bio: 'Architetto d\'interni con studio a Brera. Specializzata in ristrutturazioni residenziali e uffici di alto livello. Ha firmato oltre 120 progetti negli ultimi 10 anni.',
    specialties: ['interior design', 'ristrutturazione', 'progettazione', 'residenziale', 'uffici', 'luxury'],
    yearsInBNI: 5,
    referralsGiven: 143,
    rating: 4.9,
  },
  {
    id: 'mi-007',
    name: 'Roberto Gatti',
    profession: 'Consulente Marketing Digitale',
    category: 'Marketing',
    city: 'Milano',
    chapter: 'NDP Milano Duomo',
    phone: '+39 02 8901 2345',
    email: 'r.gatti@gattidigital.it',
    bio: 'Consulente marketing con 10 anni di esperienza in digital marketing, SEO, advertising e brand strategy per PMI e grandi aziende.',
    specialties: ['digital marketing', 'SEO', 'social media', 'Google Ads', 'brand strategy', 'e-commerce', 'contenuti'],
    yearsInBNI: 4,
    referralsGiven: 167,
    rating: 4.7,
  },
  {
    id: 'mi-008',
    name: 'Patrizia Esposito',
    profession: 'Consulente Finanziaria',
    category: 'Consulente Finanziario',
    city: 'Milano',
    chapter: 'NDP Milano Brera',
    phone: '+39 02 4567 8901',
    email: 'p.esposito@esposito-finance.it',
    bio: 'Consulente finanziaria indipendente (fee-only), iscritta OCF. Specializzata in pianificazione finanziaria personale e patrimoniale per famiglie e imprenditori.',
    specialties: ['investimenti', 'pianificazione finanziaria', 'fondi', 'pensione', 'patrimonio', 'risparmio'],
    yearsInBNI: 6,
    referralsGiven: 178,
    rating: 4.8,
  },
  {
    id: 'mi-009',
    name: 'Davide Moretti',
    profession: 'Avvocato del Lavoro',
    category: 'Avvocato',
    city: 'Milano',
    chapter: 'NDP Milano Nord',
    phone: '+39 02 7654 3210',
    email: 'd.moretti@studiolegalemoretti.it',
    bio: 'Avvocato specializzato in diritto del lavoro, gestione delle risorse umane e contratti collettivi. Assiste aziende in procedure disciplinari, licenziamenti e contenzioso.',
    specialties: ['diritto del lavoro', 'licenziamento', 'contratti', 'HR', 'mobbing', 'sindacati', 'vertenze'],
    yearsInBNI: 8,
    referralsGiven: 234,
    rating: 5.0,
  },
  {
    id: 'mi-010',
    name: 'Elena Ricci',
    profession: 'Fotografa Professionale',
    category: 'Fotografo',
    city: 'Milano',
    chapter: 'NDP Milano Nord',
    phone: '+39 02 3210 9876',
    email: 'e.ricci@elenariccifoto.it',
    bio: 'Fotografa commerciale e ritrattista. Specializzata in fotografia corporate, eventi aziendali, prodotto e architettura d\'interni per brand e agenzie.',
    specialties: ['fotografia corporate', 'eventi', 'prodotto', 'ritratti', 'architettura', 'branding visivo'],
    yearsInBNI: 3,
    referralsGiven: 87,
    rating: 4.8,
  },

  // === ROMA ===
  {
    id: 'rm-001',
    name: 'Antonio De Luca',
    profession: 'Avvocato Penalista',
    category: 'Avvocato',
    city: 'Roma',
    chapter: 'NDP Roma Centro',
    phone: '+39 06 8765 4321',
    email: 'a.deluca@studiodeluca.it',
    bio: 'Penalista con 20 anni di foro romano. Esperto in reati societari, corruzione, frode fiscale e difesa penale delle imprese. Collabora con studi internazionali.',
    specialties: ['diritto penale', 'reati societari', 'frode', 'difesa penale', 'corruzione', 'compliance'],
    yearsInBNI: 9,
    referralsGiven: 267,
    rating: 4.9,
  },
  {
    id: 'rm-002',
    name: 'Silvia Fontana',
    profession: 'Commercialista',
    category: 'Commercialista',
    city: 'Roma',
    chapter: 'NDP Roma Centro',
    phone: '+39 06 5678 9012',
    email: 's.fontana@fontanastudio.it',
    bio: 'Commercialista con doppia specializzazione in fiscalità internazionale e start-up innovative. Consulente di riferimento per enti del terzo settore e imprese estere.',
    specialties: ['fiscalità internazionale', 'startup', 'terzo settore', 'contabilità', 'bilancio', 'IRPEF', 'IRES'],
    yearsInBNI: 5,
    referralsGiven: 198,
    rating: 4.7,
  },
  {
    id: 'rm-003',
    name: 'Francesco Greco',
    profession: 'Agente Immobiliare',
    category: 'Agente Immobiliare',
    city: 'Roma',
    chapter: 'NDP Roma Parioli',
    phone: '+39 06 9012 3456',
    email: 'f.greco@grecoimmobiliare.it',
    bio: 'Agente immobiliare con 18 anni di esperienza nel mercato romano. Specializzato nei quartieri Parioli, EUR e Trastevere per clientela privata e istituzionale.',
    specialties: ['immobili Roma', 'Parioli', 'EUR', 'Trastevere', 'affitti', 'vendita', 'aste immobiliari'],
    yearsInBNI: 7,
    referralsGiven: 189,
    rating: 4.8,
  },
  {
    id: 'rm-004',
    name: 'Valentina Rizzo',
    profession: 'Coach Professionista ICF',
    category: 'Coach',
    city: 'Roma',
    chapter: 'NDP Roma Centro',
    phone: '+39 06 3456 7890',
    email: 'v.rizzo@coachingrizzo.it',
    bio: 'Executive coach certificata ICF (PCC). Accompagna manager, imprenditori e team aziendali nello sviluppo di leadership, comunicazione e performance.',
    specialties: ['executive coaching', 'leadership', 'team building', 'comunicazione', 'performance', 'change management'],
    yearsInBNI: 4,
    referralsGiven: 145,
    rating: 4.9,
  },
  {
    id: 'rm-005',
    name: 'Giorgio Mancini',
    profession: 'Ingegnere Civile',
    category: 'Ingegnere',
    city: 'Roma',
    chapter: 'NDP Roma Parioli',
    phone: '+39 06 7890 1234',
    email: 'g.mancini@manciniprogetti.it',
    bio: 'Ingegnere civile e strutturista. Esperto in progettazione strutturale, sismica e collaudi. Ha seguito interventi su oltre 200 edifici pubblici e privati.',
    specialties: ['ingegneria civile', 'strutture', 'sismica', 'collaudi', 'progettazione', 'recupero edilizio'],
    yearsInBNI: 6,
    referralsGiven: 176,
    rating: 4.8,
  },
  {
    id: 'rm-006',
    name: 'Claudia Vitale',
    profession: 'Specialista Marketing B2B',
    category: 'Marketing',
    city: 'Roma',
    chapter: 'NDP Roma Centro',
    phone: '+39 06 2345 6789',
    email: 'c.vitale@vitalemarketing.it',
    bio: 'Consulente marketing specializzata nel B2B. Sviluppa strategie di lead generation, posizionamento di brand e campagne omnicanale per aziende di medie dimensioni.',
    specialties: ['B2B marketing', 'lead generation', 'LinkedIn', 'content marketing', 'HubSpot', 'CRM'],
    yearsInBNI: 3,
    referralsGiven: 112,
    rating: 4.7,
  },
  {
    id: 'rm-007',
    name: 'Stefano Palumbo',
    profession: 'Dentista & Ortodontista',
    category: 'Dentista',
    city: 'Roma',
    chapter: 'NDP Roma Parioli',
    phone: '+39 06 6789 0123',
    email: 's.palumbo@studiopalumbo.it',
    bio: 'Dentista con specializzazione in ortodonzia invisibile e implantologia. Studio all\'avanguardia a Parioli con scanner 3D e tecnologia digitale.',
    specialties: ['ortodonzia', 'invisalign', 'implantologia', 'estetica dentale', 'sbiancamento', 'protesi'],
    yearsInBNI: 5,
    referralsGiven: 163,
    rating: 4.9,
  },
  {
    id: 'rm-008',
    name: 'Mirella Santoro',
    profession: 'Notaio',
    category: 'Notaio',
    city: 'Roma',
    chapter: 'NDP Roma Centro',
    phone: '+39 06 4321 0987',
    email: 'm.santoro@notaisantoro.it',
    bio: 'Notaio a Roma con 15 anni di esperienza in atti immobiliari, societari e successori. Assistenza completa per compravendite, mutui, testamenti e donazioni.',
    specialties: ['atti notarili', 'compravendite', 'mutui', 'testamenti', 'successioni', 'donazioni', 'società'],
    yearsInBNI: 8,
    referralsGiven: 221,
    rating: 4.8,
  },

  // === TORINO ===
  {
    id: 'to-001',
    name: 'Matteo Ferrari',
    profession: 'Consulente IT & Cloud',
    category: 'Consulente IT',
    city: 'Torino',
    chapter: 'NDP Torino Business',
    phone: '+39 011 8765 4321',
    email: 'm.ferrari@cloudferrari.it',
    bio: 'Consulente IT specializzato in migrazioni cloud (AWS, Azure), DevOps e architetture scalabili. Collabora con PMI manifatturiere torinesi nella digitalizzazione.',
    specialties: ['cloud computing', 'AWS', 'Azure', 'DevOps', 'cybersecurity', 'digital transformation', 'industria 4.0'],
    yearsInBNI: 4,
    referralsGiven: 134,
    rating: 4.8,
  },
  {
    id: 'to-002',
    name: 'Carla Russo',
    profession: 'Avvocatessa Famiglia',
    category: 'Avvocato',
    city: 'Torino',
    chapter: 'NDP Torino Business',
    phone: '+39 011 5678 9012',
    email: 'c.russo@studiorusso.it',
    bio: 'Avvocata specializzata in diritto di famiglia: separazioni, divorzi, affidamento minori e successioni. Approccio empatico e orientato alla mediazione.',
    specialties: ['diritto di famiglia', 'separazione', 'divorzio', 'affidamento', 'successioni', 'mediazione familiare'],
    yearsInBNI: 6,
    referralsGiven: 187,
    rating: 4.9,
  },
  {
    id: 'to-003',
    name: 'Paolo Negri',
    profession: 'Commercialista d\'Impresa',
    category: 'Commercialista',
    city: 'Torino',
    chapter: 'NDP Torino Nord',
    phone: '+39 011 9012 3456',
    email: 'p.negri@negristudio.it',
    bio: 'Commercialista con focus su imprese industriali e manifatturiere. Esperto in controllo di gestione, budget e crisi d\'impresa. Consulente di fiducia di 60+ aziende.',
    specialties: ['controllo di gestione', 'budget', 'crisi aziendale', 'industria', 'ristrutturazione debiti'],
    yearsInBNI: 7,
    referralsGiven: 210,
    rating: 4.8,
  },
  {
    id: 'to-004',
    name: 'Laura Benedetti',
    profession: 'Architetta',
    category: 'Architetto',
    city: 'Torino',
    chapter: 'NDP Torino Nord',
    phone: '+39 011 3456 7890',
    email: 'l.benedetti@benedettiarch.it',
    bio: 'Architetta specializzata in riqualificazione energetica ed efficienza degli edifici. Gestisce pratiche bonus edilizi, Superbonus e progettazione sostenibile.',
    specialties: ['Superbonus', 'efficienza energetica', 'ristrutturazione', 'sostenibilità', 'pratiche edilizie', 'SAP'],
    yearsInBNI: 3,
    referralsGiven: 96,
    rating: 4.7,
  },
  {
    id: 'to-005',
    name: 'Enrico Martinelli',
    profession: 'Broker Assicurativo',
    category: 'Assicuratore',
    city: 'Torino',
    chapter: 'NDP Torino Business',
    phone: '+39 011 7890 1234',
    email: 'e.martinelli@martinellibroker.it',
    bio: 'Broker assicurativo con accesso a tutti i principali mercati. Specializzato in polizze per aziende manifatturiere, flotte aziendali e rischi speciali.',
    specialties: ['assicurazioni aziendali', 'flotte', 'D&O', 'rischi industriali', 'polizze property', 'broker'],
    yearsInBNI: 5,
    referralsGiven: 172,
    rating: 4.8,
  },
  {
    id: 'to-006',
    name: 'Monica Serra',
    profession: 'Traduttrice Professionista',
    category: 'Traduttore',
    city: 'Torino',
    chapter: 'NDP Torino Nord',
    phone: '+39 011 2345 6789',
    email: 'm.serra@serratranslations.it',
    bio: 'Traduttrice giurata (EN, FR, DE) con specializzazione in documenti legali, tecnici e commerciali. Membro AIT con 15 anni di esperienza.',
    specialties: ['traduzione', 'inglese', 'francese', 'tedesco', 'documenti legali', 'tecnica', 'giurata'],
    yearsInBNI: 4,
    referralsGiven: 128,
    rating: 4.9,
  },

  // === FIRENZE ===
  {
    id: 'fi-001',
    name: 'Gianluca Bartoli',
    profession: 'Agente Immobiliare Luxury',
    category: 'Agente Immobiliare',
    city: 'Firenze',
    chapter: 'NDP Firenze Renaissance',
    phone: '+39 055 8765 4321',
    email: 'g.bartoli@bartolicasefiorentine.it',
    bio: 'Leader nel mercato immobiliare fiorentino di lusso. Specializzato in ville, casali e appartamenti storici nel centro storico UNESCO e sulle colline del Chianti.',
    specialties: ['ville', 'casali', 'centro storico', 'Chianti', 'investimento immobiliare', 'clientela internazionale'],
    yearsInBNI: 8,
    referralsGiven: 234,
    rating: 4.9,
  },
  {
    id: 'fi-002',
    name: 'Alessandra Pellegrini',
    profession: 'Dentista Estetica',
    category: 'Dentista',
    city: 'Firenze',
    chapter: 'NDP Firenze Renaissance',
    phone: '+39 055 5678 9012',
    email: 'a.pellegrini@pellegrinisorridenti.it',
    bio: 'Dentista specializzata in odontoiatria estetica e riabilitativa. Lo studio è centro certificato per allineatori invisibili e faccette in ceramica.',
    specialties: ['estetica dentale', 'faccette', 'sbiancamento', 'allineatori', 'gengive', 'protesi fissa'],
    yearsInBNI: 4,
    referralsGiven: 143,
    rating: 4.8,
  },
  {
    id: 'fi-003',
    name: 'Tommaso Innocenti',
    profession: 'Consulente Finanziario',
    category: 'Consulente Finanziario',
    city: 'Firenze',
    chapter: 'NDP Firenze Renaissance',
    phone: '+39 055 9012 3456',
    email: 't.innocenti@innocentiwealth.it',
    bio: 'Consulente patrimoniale per famiglie imprenditoriali toscane. Pianificazione del passaggio generazionale, investimenti ESG e ottimizzazione fiscale del patrimonio.',
    specialties: ['pianificazione patrimoniale', 'passaggio generazionale', 'ESG', 'family office', 'investimenti'],
    yearsInBNI: 6,
    referralsGiven: 167,
    rating: 4.8,
  },
  {
    id: 'fi-004',
    name: 'Serena Marini',
    profession: 'Consulente Marketing & Brand',
    category: 'Marketing',
    city: 'Firenze',
    chapter: 'NDP Firenze Renaissance',
    phone: '+39 055 3456 7890',
    email: 's.marini@marinibrand.it',
    bio: 'Specialista in brand identity e comunicazione per aziende della moda e del made-in-Italy. Ha collaborato con brand internazionali in settori luxury e food.',
    specialties: ['brand identity', 'moda', 'made in Italy', 'luxury', 'storytelling', 'social media', 'eventi'],
    yearsInBNI: 3,
    referralsGiven: 109,
    rating: 4.7,
  },
  {
    id: 'fi-005',
    name: 'Bruno Cattaneo',
    profession: 'Notaio',
    category: 'Notaio',
    city: 'Firenze',
    chapter: 'NDP Firenze Renaissance',
    phone: '+39 055 7890 1234',
    email: 'b.cattaneo@notaiocattaneo.it',
    bio: 'Notaio a Firenze con grande esperienza in atti di compravendita immobiliare, costituzione di società e operazioni straordinarie d\'impresa.',
    specialties: ['compravendita', 'società', 'operazioni straordinarie', 'successioni', 'trust', 'vincoli di destinazione'],
    yearsInBNI: 9,
    referralsGiven: 245,
    rating: 4.9,
  },

  // === BOLOGNA ===
  {
    id: 'bo-001',
    name: 'Andrea Zanetti',
    profession: 'Avvocato Commerciale',
    category: 'Avvocato',
    city: 'Bologna',
    chapter: 'NDP Bologna Emilia',
    phone: '+39 051 8765 4321',
    email: 'a.zanetti@zanettilaw.it',
    bio: 'Avvocato commerciale con focus su contratti internazionali, distribuzione e franchising. Consiglia aziende del settore alimentare e manifatturiero emiliano.',
    specialties: ['contratti commerciali', 'distribuzione', 'franchising', 'internazionale', 'food', 'manifattura'],
    yearsInBNI: 5,
    referralsGiven: 178,
    rating: 4.8,
  },
  {
    id: 'bo-002',
    name: 'Francesca Neri',
    profession: 'Commercialista Startup',
    category: 'Commercialista',
    city: 'Bologna',
    chapter: 'NDP Bologna Emilia',
    phone: '+39 051 5678 9012',
    email: 'f.neri@neristudiocomm.it',
    bio: 'Commercialista specializzata in startup innovative e PMI tech. Supporto in fundraising, agevolazioni fiscali per R&D, e contabilità per scale-up.',
    specialties: ['startup', 'R&D', 'agevolazioni fiscali', 'Industria 4.0', 'credito d\'imposta', 'investitori'],
    yearsInBNI: 3,
    referralsGiven: 112,
    rating: 4.7,
  },
  {
    id: 'bo-003',
    name: 'Stefano Ruggi',
    profession: 'Consulente IT & AI',
    category: 'Consulente IT',
    city: 'Bologna',
    chapter: 'NDP Bologna Emilia',
    phone: '+39 051 9012 3456',
    email: 's.ruggi@ruggitech.it',
    bio: 'Consulente IT specializzato in intelligenza artificiale e machine learning per aziende manifatturiere. Progetti di computer vision, predizione guasti e ottimizzazione processi.',
    specialties: ['intelligenza artificiale', 'machine learning', 'computer vision', 'IoT', 'Industry 4.0', 'automazione'],
    yearsInBNI: 2,
    referralsGiven: 67,
    rating: 4.8,
  },
  {
    id: 'bo-004',
    name: 'Isabella Fabbri',
    profession: 'Assicuratrice',
    category: 'Assicuratore',
    city: 'Bologna',
    chapter: 'NDP Bologna Nord',
    phone: '+39 051 3456 7890',
    email: 'i.fabbri@fabbriassicura.it',
    bio: 'Agente assicurativo con portafoglio di 400+ clienti. Specializzata in tutela legale, RC auto e polizze per professionisti e studi associati.',
    specialties: ['tutela legale', 'RC auto', 'polizze professionisti', 'vita', 'infortuni', 'malattia'],
    yearsInBNI: 5,
    referralsGiven: 189,
    rating: 4.7,
  },
  {
    id: 'bo-005',
    name: 'Nicola Tosi',
    profession: 'Coach & Formatore',
    category: 'Coach',
    city: 'Bologna',
    chapter: 'NDP Bologna Nord',
    phone: '+39 051 7890 1234',
    email: 'n.tosi@tosiformazione.it',
    bio: 'Business coach e formatore aziendale. Programmi di vendita, leadership e comunicazione per team commerciali. Oltre 3.000 ore di aula negli ultimi 5 anni.',
    specialties: ['formazione vendita', 'leadership', 'comunicazione efficace', 'team management', 'motivazione'],
    yearsInBNI: 4,
    referralsGiven: 134,
    rating: 4.8,
  },

  // === NAPOLI ===
  {
    id: 'na-001',
    name: 'Ciro Esposito',
    profession: 'Avvocato Immobiliare',
    category: 'Avvocato',
    city: 'Napoli',
    chapter: 'NDP Napoli Partenope',
    phone: '+39 081 8765 4321',
    email: 'c.esposito@esposito-legale.it',
    bio: 'Avvocato specializzato in diritto immobiliare, urbanistica e recupero crediti. Assiste privati e sviluppatori in operazioni di acquisto, locazione e contenzioso.',
    specialties: ['diritto immobiliare', 'urbanistica', 'recupero crediti', 'locazioni', 'condominio', 'esproprio'],
    yearsInBNI: 6,
    referralsGiven: 198,
    rating: 4.8,
  },
  {
    id: 'na-002',
    name: 'Rosaria Ferrara',
    profession: 'Agente Immobiliare',
    category: 'Agente Immobiliare',
    city: 'Napoli',
    chapter: 'NDP Napoli Partenope',
    phone: '+39 081 5678 9012',
    email: 'r.ferrara@ferraracasa.it',
    bio: 'Agente immobiliare con 14 anni di attività nel mercato napoletano. Esperta in immobili storici del centro, Chiaia e Posillipo. Rete di investitori locali e internazionali.',
    specialties: ['Chiaia', 'Posillipo', 'centro storico', 'immobili storici', 'investimento', 'affitti brevi'],
    yearsInBNI: 5,
    referralsGiven: 156,
    rating: 4.7,
  },
  {
    id: 'na-003',
    name: 'Luigi De Rosa',
    profession: 'Commercialista & Tributarista',
    category: 'Commercialista',
    city: 'Napoli',
    chapter: 'NDP Napoli Partenope',
    phone: '+39 081 9012 3456',
    email: 'l.derosa@studioderosa.it',
    bio: 'Commercialista e tributarista con forte esperienza in aziende del settore turistico e ristorazione. Specializzato in contenzioso tributario e accordi con l\'Agenzia delle Entrate.',
    specialties: ['tributario', 'turismo', 'ristorazione', 'contenzioso', 'concordato preventivo', 'agenzia entrate'],
    yearsInBNI: 7,
    referralsGiven: 213,
    rating: 4.8,
  },
  {
    id: 'na-004',
    name: 'Concetta Amendola',
    profession: 'Medico di Base & Wellness',
    category: 'Medico',
    city: 'Napoli',
    chapter: 'NDP Napoli Partenope',
    phone: '+39 081 3456 7890',
    email: 'c.amendola@dottamendola.it',
    bio: 'Medico di medicina generale con ambulatorio privato. Specializzata in medicina preventiva, nutrizione clinica e gestione dello stress per professionisti e manager.',
    specialties: ['medicina preventiva', 'nutrizione', 'stress management', 'check-up', 'benessere', 'salute aziendale'],
    yearsInBNI: 3,
    referralsGiven: 89,
    rating: 4.9,
  },

  // === VENEZIA ===
  {
    id: 've-001',
    name: 'Marco Trevisan',
    profession: 'Consulente Finanziario',
    category: 'Consulente Finanziario',
    city: 'Venezia',
    chapter: 'NDP Venezia Serenissima',
    phone: '+39 041 8765 4321',
    email: 'm.trevisan@trevisan-finance.it',
    bio: 'Consulente finanziario indipendente specializzato in imprenditori e famiglie del Nordest. Ottimizzazione fiscale, pianificazione successoria e portafogli ESG.',
    specialties: ['finanza personale', 'imprenditori', 'successione', 'ESG', 'portafogli', 'ottimizzazione fiscale'],
    yearsInBNI: 5,
    referralsGiven: 167,
    rating: 4.8,
  },
  {
    id: 've-002',
    name: 'Giovanna Zorzi',
    profession: 'Architetta & Interior Design',
    category: 'Architetto',
    city: 'Venezia',
    chapter: 'NDP Venezia Serenissima',
    phone: '+39 041 5678 9012',
    email: 'g.zorzi@zorziarchitettura.it',
    bio: 'Architetta specializzata in ristrutturazione di palazzi storici veneziani e B&B di lusso. Lavora con proprietà vincolate dalla Soprintendenza con grande esperienza burocratica.',
    specialties: ['palazzi storici', 'Venezia', 'Soprintendenza', 'B&B', 'luxury', 'ristrutturazione', 'vincoli artistici'],
    yearsInBNI: 6,
    referralsGiven: 143,
    rating: 4.9,
  },

  // === GENOVA ===
  {
    id: 'ge-001',
    name: 'Roberto Parodi',
    profession: 'Broker Assicurativo',
    category: 'Assicuratore',
    city: 'Genova',
    chapter: 'NDP Genova Porto',
    phone: '+39 010 8765 4321',
    email: 'r.parodi@parodibroker.it',
    bio: 'Broker assicurativo specializzato in rischi marittimi, cargo e logistica. Collabora con armatori, spedizionieri e aziende del settore portuale genovese.',
    specialties: ['assicurazioni maritime', 'cargo', 'logistica', 'porto', 'armatori', 'spedizioni', 'hull & machinery'],
    yearsInBNI: 8,
    referralsGiven: 234,
    rating: 4.9,
  },
  {
    id: 'ge-002',
    name: 'Cristina Baudino',
    profession: 'Consulente Marketing',
    category: 'Marketing',
    city: 'Genova',
    chapter: 'NDP Genova Porto',
    phone: '+39 010 5678 9012',
    email: 'c.baudino@baudinomktg.it',
    bio: 'Consulente marketing con specializzazione in settore nautico, portuale e export. Strategie di internazionalizzazione e digital per aziende del Nordovest.',
    specialties: ['marketing internazionale', 'export', 'nautica', 'portuale', 'B2B', 'fiere internazionali'],
    yearsInBNI: 4,
    referralsGiven: 123,
    rating: 4.7,
  },
];

export const chapters: Chapter[] = [
  {
    id: 'ch-mi-001',
    name: 'NDP Milano Duomo',
    city: 'Milano',
    meetingDay: 'Mercoledì',
    meetingTime: '07:00',
    memberCount: 42,
    topCategories: ['Avvocato', 'Commercialista', 'Consulente IT', 'Marketing', 'Consulente Finanziario'],
    founded: 2016,
    description: 'Il capitolo storico di Milano, cuore del business networking nel distretto finanziario. Riunione settimanale con colazione di lavoro al Grand Hotel et de Milan.',
  },
  {
    id: 'ch-mi-002',
    name: 'NDP Milano Brera',
    city: 'Milano',
    meetingDay: 'Giovedì',
    meetingTime: '07:30',
    memberCount: 38,
    topCategories: ['Architetto', 'Agente Immobiliare', 'Assicuratore', 'Fotografo', 'Marketing'],
    founded: 2018,
    description: 'Il capitolo più creativo di Milano, nel quartiere delle gallerie e dei design studio. Ideale per professionisti del mondo visual, immobiliare e creativo.',
  },
  {
    id: 'ch-mi-003',
    name: 'NDP Milano Nord',
    city: 'Milano',
    meetingDay: 'Martedì',
    meetingTime: '07:00',
    memberCount: 35,
    topCategories: ['Ingegnere', 'Consulente IT', 'Avvocato', 'Fotografo', 'Coach'],
    founded: 2020,
    description: 'Capitolo dinamico nell\'area di Sesto San Giovanni e Monza Brianza. Focus su PMI manifatturiere e professionisti tecnici del Nord Milano.',
  },
  {
    id: 'ch-rm-001',
    name: 'NDP Roma Centro',
    city: 'Roma',
    meetingDay: 'Mercoledì',
    meetingTime: '07:00',
    memberCount: 44,
    topCategories: ['Avvocato', 'Notaio', 'Commercialista', 'Coach', 'Marketing'],
    founded: 2015,
    description: 'Il capitolo più grande e longevo della Capitale. Situato nel quartiere Prati, raduna professionisti delle professioni legali, fiscali e consulenziali romane.',
  },
  {
    id: 'ch-rm-002',
    name: 'NDP Roma Parioli',
    city: 'Roma',
    meetingDay: 'Venerdì',
    meetingTime: '07:30',
    memberCount: 31,
    topCategories: ['Dentista', 'Medico', 'Agente Immobiliare', 'Consulente Finanziario', 'Ingegnere'],
    founded: 2019,
    description: 'Capitolo esclusivo nel cuore di Parioli. Professionisti dell\'area sanitaria, immobiliare di lusso e finanza per una clientela di alto profilo.',
  },
  {
    id: 'ch-to-001',
    name: 'NDP Torino Business',
    city: 'Torino',
    meetingDay: 'Giovedì',
    meetingTime: '07:00',
    memberCount: 39,
    topCategories: ['Commercialista', 'Avvocato', 'Assicuratore', 'Consulente IT', 'Coach'],
    founded: 2017,
    description: 'Il capitolo di riferimento per il business torinese. Network di imprenditori e professionisti legati al distretto automotive, aerospaziale e manifatturiero.',
  },
  {
    id: 'ch-to-002',
    name: 'NDP Torino Nord',
    city: 'Torino',
    meetingDay: 'Martedì',
    meetingTime: '07:30',
    memberCount: 28,
    topCategories: ['Architetto', 'Ingegnere', 'Traduttore', 'Commercialista', 'Marketing'],
    founded: 2021,
    description: 'Capitolo giovane e in forte crescita nell\'area nord di Torino. Specializzato in professioni tecniche e innovative con forte vocazione internazionale.',
  },
  {
    id: 'ch-fi-001',
    name: 'NDP Firenze Renaissance',
    city: 'Firenze',
    meetingDay: 'Mercoledì',
    meetingTime: '07:00',
    memberCount: 36,
    topCategories: ['Agente Immobiliare', 'Notaio', 'Commercialista', 'Marketing', 'Dentista'],
    founded: 2016,
    description: 'L\'unico capitolo NDP di Firenze, punto di incontro per professionisti del rinascimento toscano. Focus su immobiliare di pregio, moda, arte e turismo di lusso.',
  },
  {
    id: 'ch-bo-001',
    name: 'NDP Bologna Emilia',
    city: 'Bologna',
    meetingDay: 'Venerdì',
    meetingTime: '07:00',
    memberCount: 33,
    topCategories: ['Avvocato', 'Commercialista', 'Consulente IT', 'Coach', 'Assicuratore'],
    founded: 2018,
    description: 'Il cuore del networking emiliano. Professionisti del food, motor valley e startup ecosystem bolognese si incontrano ogni venerdì mattina.',
  },
  {
    id: 'ch-na-001',
    name: 'NDP Napoli Partenope',
    city: 'Napoli',
    meetingDay: 'Mercoledì',
    meetingTime: '07:30',
    memberCount: 41,
    topCategories: ['Avvocato', 'Commercialista', 'Agente Immobiliare', 'Medico', 'Coach'],
    founded: 2017,
    description: 'Il capitolo più vivace del Sud Italia. Imprenditori e professionisti napoletani costruiscono relazioni forti e generano business reale ogni settimana.',
  },
];
